application: pageforest
version: default
runtime: python
api_version: 1

handlers:
- url: /remote_api_hidden
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /static
  static_dir: static

- url: /.*
  script: main.py

skip_files:
- ^local/
- ^app\.yaml$
- ^index\.yaml$
- \#$
- ~$
- \.py[co]$
- ^(.*/)?\.
- \.bak$
- \.orig$
