application: pageforest
version: dev
runtime: python
api_version: 1
default_expiration: 30d

handlers:
- url: /remote_api_hidden
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /static
  static_dir: static

- url: /code/widget.js
  static_files: static/js/widget.js
  upload: static/js/widget.js

- url: /.*
  script: main.py

skip_files:
- ^local/
- ^app\.yaml$
- ^index\.yaml$
- ^.*\#$
- ^.*~$
- ^.*\.py[co]$
- ^(.*/)?\.
- ^.*\.bak$
- ^.*\.orig$
