application: pageforest
version: default
runtime: python
api_version: 1

handlers:
- url: /remote_api_hidden
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /stats/.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: main.py
