#!/bin/bash

sudo apt-get install sqlite
sudo apt-get install libsqlite3-dev
sudo easy_install pep8
sudo easy_install mock

# Install OpenSSL
read -p "Install Open SSL (y/n): "
if [ "$REPLY" = "y" ]; then
    cd $HOME/Downloads
    wget http://www.openssl.org/source/openssl-0.9.8g.tar.gz

    cs $HOME/src
    tar -xzvf $HOME/Downloads/openssl-0.9.8g.tar.gz

    cd openssl-0.9.8g.tar.gz
    ./config
    make
    sudo make install
fi

# Get Python 2.5.2
read -p "Install Python 2.5.2 (y/n): "
if [ "$REPLY" = "y" ]; then
    cd $HOME/Downloads
    if [ ! -f Python-2.5.2.tgz ]; then
        wget http://www.python.org/ftp/python/2.5.2/Python-2.5.2.tgz
        cd $HOME/src
        tar -xzvf $HOME/Downloads/Python-2.5.2.tgz
    fi

    cd $HOME/src/Python-2.5.2
    ./configure
    make clean
    make
    sudo make altinstall
fi

# Get SSL Library not supported in native 2.5.2
read -p "Install Python ssl Library (y/n): "
if [ "$REPLY" = "y" ]; then
    cd $HOME/Downloads
    if [! -f ssl-1.15.tar.gz ]; then
        wget http://pypi.python.org/packages/source/s/ssl/ssl-1.15.tar.gz
        cd $HOME/src
        tar -xzvf $HOME/Downloads/ssl-1.15.tar.gz
    fi

    cd $HOME/src/ssl-1.15
    sudo python2.5 setup.py install
fi

# Get Django 1.1
read -p "Install Django 1.1 (y/n): "
if [ "$REPLY" = "y" ]; then
    cd $HOME/Downloads
    if [! -f Django-1.1.2.tar.gz ]; then
        wget  http://media.djangoproject.com/releases/1.1/Django-1.1.2.tar.gz
        cd $HOME/src
        tar -xzvf $HOME/Downloads/Django-1.1.2.tar.gz
    fi

    cd $HOME/src/Django-1.1.2
    sudo python2.5 setup.py install
fi

# Get AppEngine - needs to be in /usr/local for django helper to find properly?
read -p "Install App Engine (y/n): "
if [ "$REPLY" = "y" ]; then
    cd $HOME/Downloads
    if [ ! -f google_appengine_1.3.8.zip ]; then
        wget http://googleappengine.googlecode.com/files/google_appengine_1.3.8.zip
    fi

    cd /usr/local
    sudo unzip $HOME/Downloads/google_appengine_1.3.8.zip
    sudo chmod -R o+rx google_appengine

    # Is this copy really needed?  Just using for lint.py not to warn.
    # sudo cp -r google_appengine/google /usr/local/lib/python2.5/site-packages/

    cd /usr/local/bin

    # Put dev_appserver.py and appcfg.py directly into PATH
    sudo ln -f -s /usr/local/google_appengine/dev_appserver.py
    sudo ln -f -s /usr/local/google_appengine/appcfg.py
fi

read -p "Install App Engine Helper (y/n): "
if [ "$REPLY" = "y" ]; then
    cd $HOME/Downloads
    if [ ! -f appengine_helper_for_django-r105.zip ]; then
        wget  http://google-app-engine-django.googlecode.com/files/appengine_helper_for_django-r105.zip
    fi

    cd /usr/local
    sudo unzip $HOME/Downloads/appengine_helper_for_django-r105.zip
    sudo chmod -R o+rwx appengine_helper_for_django

    # Remove slow or mis-behaving tests
    cd appengine_helper_for_django/appengine_django/tests
    rm commands_test.py integration_test.py serialization_test.py

    # Do we need a copy in site packages?
    # cd /usr/local/lib/python2.5/site-packages
    # sudo cp -r /usr/local/appengine_helper_for_django/appengine_django .
fi
